- apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
> 디자이너의 요구로 인해 원서 접수 성적 입력 페이지에서 과목 추가 시 자동으로 아래로 스크롤하는 기능을 없앴습니다.
https://github.com/Bamdoliro/marururu/assets/102217839/b277c221-29ba-4462-be3d-0ffc47b3efb6
<br>
-
<br>
> 원서 접수 성적 입력 페이지에서 과목 추가 시 자동 스크롤하는 기능 없앴습니다

- apps/user/src/components/notice/NoticeDetailContent/NoticeDetailContent.tsx
- packages/maru-theme/src/global.ts
- packages/maru-utils/functions/convertLink.ts
- packages/maru-utils/index.ts
> 공지사항 Content 링크 처리

- apps/user/src/components/common/Header/Header.tsx
- apps/user/src/components/main/Schedule/Schedule.tsx
- apps/user/src/components/main/Schedule/ScheduleItem/ScheduleItem.tsx
> 바뀐 헤더, 메인페이지 스케줄의 디자인을 반영했습니다.
헤더의 높이를 126px -> 118px로 바꿨고
스케줄의 gap 속성의 값을 수정했습니다.
<br>
-
<br>
> 바뀐 헤더, 메인페이지 스케줄 디자인 반영하기

- apps/user/src/app/score-simulation/page.tsx
- apps/user/src/components/form/ProgressSteps/ProgressSteps.tsx
- apps/user/src/layouts/AppLayout.tsx
> AppLayout에 StyledAppLayout 컴포넌트의  높이를 `min-height(100vh-118px)`로 수정했습니다.
<br>
-
<br>
https://github.com/Bamdoliro/marururu/assets/102217839/92d51a0a-1b17-4658-8560-954baca87cdf
> AppLayout에 StyledAppLayout 컴포넌트의  높이를 수정했습니다.

- apps/admin/src/app/page.tsx
- apps/admin/src/components/form/ExportExcelModal/ExportExcelModal.hooks.tsx
- apps/admin/src/components/form/ExportExcelModal/ExportExcelModal.tsx
- apps/admin/src/components/form/SecondScoreUploadModal/SecondScoreUploadModal.tsx
- apps/admin/src/components/form/SecondScoreUploader/SecondScoreUploader.tsx
- apps/admin/src/constants/common/constant.ts
- apps/admin/src/services/form/api.ts
- apps/admin/src/services/form/queries.ts
- apps/admin/src/types/form/client.ts
> 어드민 원서 관리 엑셀 내보내기 기능을 개발했습니다.
<br>
- 어드민 원서 관리 엑셀 내보내기 기능 개발
<br>
https://github.com/Bamdoliro/marururu/assets/102217839/730c1846-ea87-4e65-9ace-4fb65b9afc2e
> 어드민 원서 관리 엑셀 내보내기 기능 개발

- apps/admin/src/app/faq/[id]/page.tsx
- apps/user/src/hooks/useApiError.ts
- packages/maru-ui/src/Loader/Loader.tsx
- pnpm-lock.yaml
> 유저 에러 핸들링 안되는 버그를 수정하였습니다
<br>
- 유저 에러 핸들링 안되는 버그 수정
<br>
데이터 보내주는 방식이 달라져서 에러 핸들링이 안되었던거였숩니당
https://github.com/Bamdoliro/marururu/assets/102217654/343a3f41-8a77-45ad-a437-78dcf1f272ba
> 유저 에러 핸들링 안되는 버그 수정

- apps/admin/src/components/form/FormDetailContent/FormStatus/FormStatus.tsx
- apps/admin/src/components/form/FormDetailContent/성적/교과성적/교과성적.tsx
- apps/admin/src/components/form/FormDetailContent/성적/교과성적/교과성적Header/교과성적Header.tsx
- apps/admin/src/components/form/FormDetailContent/성적/봉사시간/봉사시간.tsx
- apps/admin/src/components/form/FormDetailContent/성적/성적.tsx
- apps/admin/src/components/form/FormDetailContent/성적/자격증/자격증.tsx
- apps/admin/src/components/form/FormDetailContent/성적/출결상황/출결상황.tsx
- packages/maru-ui/src/Input/SearchInput.tsx
> 어드민 원서 상세조회 페이지에 성적 테이블을 개발했습니다.
<br>
- 어드민 원서 상세조회 페이지 성적 테이블 개발
<br>
> 어드민 원서 상세조회 페이지 성적 테이블 개발

- apps/user/next.config.js
- apps/user/src/app/layout.tsx
- apps/user/src/lib/registry.tsx
> 레이아웃 쉬프트 현상 수정하였습니다
<br>
<br>
> 레이아웃 쉬프트 현상 수정

- apps/user/src/app/fair/page.tsx
- apps/user/src/components/fair/FairList/ApplyingItem/ApplyingItem.tsx
- apps/user/src/components/fair/FairList/ApplyingList.tsx
- apps/user/src/components/fair/FairList/ClosedItem/ClosedItem.tsx
- apps/user/src/components/fair/FairList/ClosedList.tsx
- apps/user/src/components/fair/Header/header.tsx
- apps/user/src/components/fair/index.ts
- apps/user/src/components/main/ApplicationBox/ApplicationBox.tsx
- apps/user/src/constants/common/constant.ts
- apps/user/src/services/fair/api.ts
- apps/user/src/services/fair/queries.ts
- apps/user/src/types/fair/client.ts
- apps/user/src/types/fair/remote.ts
- apps/user/src/utils/formatApplicationDate.ts
- apps/user/src/utils/formatStartDate.ts
- apps/user/src/utils/formatStatus.ts
- apps/user/src/utils/index.ts
> 일정 페에지로 이동하도록 코드 수정
> 일정 데이터 가져오기
> 일정 데이터 가공하기
<br>
- 일정상태가 진행 중이거나 진행 전, null이면 진행 중인 신청 탭에 일정상태가 마감이나 조기마감이라면 마감된 신청 탭에 각각 아이템들이 뜨도록 개발했습니다.
- 일정이 2개라면 가로 한줄로 뜨지만 3개 이상이라면 그 밑으로 보이도록 개발했습니다.
<br>
추후 백엔드에서 구글폼url을 생성할때 저장하면 이를 불러와서 구글폼으로 이어지도록 개발 예정
(올해는 시간적 문제로 신청은 마루 대신 구글폼으로 받기로 했습니다.)
> feat(user): 입학설명회 일정 페이지 개발

- apps/admin/src/constants/common/constant.ts
- apps/admin/src/hocs/withAuth.tsx
- apps/admin/src/services/auth/api.ts
- apps/admin/src/services/auth/mutations.ts
- apps/admin/src/services/auth/queries.ts
- apps/admin/src/types/auth/client.ts
- apps/admin/src/types/auth/remote.ts
> 어드민에서 로그아웃 버튼을 눌렀을 때 alert가 뜨지 않고 곧바로 로그인 페이지로 이동하도록 수정하였습니다.
> 어드민 페이지에 유저 계정으로 들어올 시 리다이렉트 기능을 추가 하였습니다.
<br>
- 로그아웃 버튼을 누르실 로그인 페이지로 이동하도록 수정
- 로그인 타입이 어드민인지 유저인지 조회하는 기능 추가
- 어드민 페이지 유저 리다이렉트 기능 추가
<br>
> feat(admin): 로그아웃 시 로그인 페이지로 이동 및 유저 리다이렉트 기능 추가

- apps/user/src/app/form/출신학교및학력/출신학교및학력.hooks.ts
- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
>졸업 연도와 합격 연도의 맞춤법이 틀려서 수정하고 입력할때 문자와 특수문자는 입력되지 않고 숫자만 입력가능하도록 수정하였습니다.
<br>
- 졸업 연도, 합격 연도 맞춤법 수정
- 숫자만 입력 가능하도록 수정
<br>
> bug(user): 졸업연도 라벨 수정 및 입력 수정

- apps/user/src/components/form/DraftFormConfirm/DraftFormConfirm.tsx
> 초안 작성이 완료되면 다음으로 넘어가기 전에 유저가 정해진 값을 입력해야지만 다음 단계로 넘어가도록 하는데 정해진 값이 아니면 아무런 이벤트도 없었는데 이를 수정하였습니다.
<br>
-정해진 값이 아니면 alert를 띄우도록 수정
<br>
> fix(user): 작성한 값이 정해진 문구와 다르면 alert띄움

- apps/user/src/components/form/FindAddressModal/FindAddressModal.tsx
- packages/ui/src/Modal/Modal.tsx
>모달이 열리면 스크롤을 하면 뒤에 화면이 불필요하게 스크롤되는 현상이 있었는데 이를 수정하였습니다.
<br>
-모달 열리면 뒤 화면 스크롤 안되도록 수정
<br>
> fix(user): 모달을 띄우고 뒤화면 스크롤 현상 수정

- apps/user/src/hooks/useGradeCaculation.ts
> 컴퓨터 활용 등급 자격증은 가장 높은 등급의 자격증만 점수로 인정하지만 높은 등급과 낮은 등급 둘 다 중복으로 인정하는 의도하지 않은 상황이 발생 했습니다. 컴퓨터 활용 등급 자격증 중복으로 인정이 안되게 수정 하였습니다.
<br>
- 컴활 자격증 중복 인정 안되게 수정
<br>
> fix(user): 컴활 자격증 중복 인정 안되게 수정

- apps/user/src/app/form/최종제출/최종제출.hooks.ts
> 원서가 처음에 loader를 통해서 다운로드되고 사용자가 선택적으로 원서를 다운로드할수 있는 버튼에서만 다운로드가 가능해야 하는데 원서 업로드하고 나서 최종제출하고 나서 4개 정도의 원서가 추가적으로 다운로드 되는 현상을 수정하였습니다.
<br>
- 로드에서만 다운로드되도록 수정
- 버튼 클릭시 추가 다운로드 가능하도록 수정
- 업로드및 최종 제출시 추가 다운로드 안되도록 수정
<br>
> fix(user): 최종 원서 여러번 다운로드

- apps/admin/src/components/form/FormDetailContent/FormStatus/FormStatus.tsx
> 초안 제출 상태인 지원자의 '제출 서류 조회' 버튼을 누르면 alert가 띄워지게 하였습니다.
<br>
- 원서 상태로 초안 제출일 경우 alert
<br>
https://github.com/Bamdoliro/marururu/assets/128698348/dee4c933-d18f-4837-8548-5d4bcfd4d899
> feat(admin): 초안 제출 제출 서류 조회 시 alert 추가

- apps/admin/src/components/common/SideBar/SideBar.tsx
- apps/admin/src/components/form/FormDetailContent/Profile/Profile.tsx
- apps/admin/src/components/form/FormTable/FormTable.tsx
- apps/admin/src/components/form/FormTable/FormTableHeader/FormTableHeader.tsx
- apps/admin/src/components/form/FormTable/FormTableItem/FormTableItem.tsx
- apps/admin/src/mocks/handlers/main.ts
- apps/admin/src/types/form/client.ts
> 원서관리 및 상세 원서 페이지에서 이름과 접수번호로 나타났던것들을 수험번호로 보이도록 수정하도록했습니다.
<br>
- 원서관리 페이지 접수번호를 수험번호로 수정
- 상세 원서페이지에서 이름을 수험번호로 수정
<br>
https://github.com/Bamdoliro/marururu/assets/126876363/741c9676-98a9-41f5-9589-2aff27d0ec0a
> fix(admin): 접수번호를 수험번호로 보이도록 수정

- apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
- apps/user/src/app/form/지원자정보/지원자정보.tsx
> 사용자 개선을 위해서 로그인한 유저의 전번과 이름을 가져와서 자동으로 입력되고 이걸로 원서를 작성하도록 하였습니다. 또한, 이름과 전번이 자동으로 입력된 후 수정할 수 없도록 하였습니다.
<br>
- 로그인한 유저의 이름 가져와 input의 value 수정
- 로그인한 유저의 전화번호을 가져와 input의 value 수정
<br>
> fix(user): 로그인한 유저가 원서를 작성할때 이름과 전화번호는 자동으로 입력되어 있도록 수정

- apps/user/src/components/common/Wrappers/FormWrapper/FormStatusManager/FormStatusManager.tsx
> 원래는 FINAL_SUBMITTED 만이 최종제출완료 페이지에 접근 하게 되었는데, 이제 RECEIVED와 APPROVED도 최종제출완료 페이지에 접근 하게 되었습니다.
<br>
- 원서 상태에 따른 원서 작성-최종제출완료 페이지 접근 상태 확대
<br>
> fix(user): 원서상태에 따른 원서작성 접근 변경

- apps/user/src/hooks/useGradeCaculation.ts
> 2024년도 기준, 국어와 영어 그리고 수학의 성취도가 '-'일 경우 'C' 점수로 처리 하되 화면에는 '-'으로 유지하는 기능을 추가 하였습니다.
<br>
- 국어와 수학 그리고 영어가 '-'인 경우에 'C'점수로 처리
- 국어와 수학 그리고 영어가 '-'인 경우에도 평균에 포함되도록 처리
<br>
> fix(user): 특정 과목 성취도가 '-'일 경우 'C'로 처리 하는 기능 추가

- apps/user/src/components/form/DraftFormConfirm/DraftFormConfirm.tsx
- packages/ui/src/Button/Button.tsx
- packages/ui/src/Confirm/Confirm.tsx
> 초안제출 시 경고문구가 날카롭다는 교무부의 의견반영으로 수정하였습니다. 또, 확인했습니다라는 문구를 정확하게 입력하지않으면 제출 버튼이 활성화가 되지 않는 형식으로 수정하였습니다.
<br>
- 경고문구 수정
- 값이 정확하지 않으면 버튼 비활성화
<br>
https://github.com/Bamdoliro/marururu/assets/126876363/85c3d661-cabe-4e49-8272-a46d1c858a71
> fix(user): 초안제출 경고 문구 수정 및 버튼 수정

- apps/admin/src/components/analysis/ApplyingType/ApplyingTypeDetail/ApplyingTypeDetail.tsx
- apps/admin/src/components/analysis/GradeDistribution/FinalRoundPassed/FinalRoundPassedDetail.tsx
- apps/admin/src/components/analysis/GradeDistribution/FirstRoundPassed/FirstRoundPassedDetail.tsx
- apps/admin/src/components/analysis/GradeDistribution/SecondRoundPassed/SecondRoundPassedDetail.tsx
- apps/admin/src/components/analysis/NumberOfApplicants/NumberOfApplicantsDetail/NumberOfApplicantsDetail.tsx
- apps/admin/src/constants/main/constants.ts
- apps/user/src/app/form/전형선택/전형선택.tsx
> 2025학년도 입학 전형 요강에 따라 이름을 변경 했습니다.
> 북한이탈청소년이 기회균등전형에서 사회다양성전형으로 변경되어 반영 하였습니다.
<br>
- 전형별 명칭 변경 
- 북한이탈청소년 전형을 사회다양성 전형으로 변경
<br>
> fix(admin): 입학 전형 요강에 따른 원서 타입 명칭 변경

- apps/user/src/hooks/useGradeCaculation.ts
> 기존에 국어,수학,영어의 성취도가 없을 시 C 성적으로 산출되도록 해야하여 이를 수정하였습니다. 하지만 테스트 도중 수학은 *2해주어야 한다는 예외 처리를 하지 않아 잘 못 계산 되고 있었습니다. 그래서 이번에 예외를 추가하여 수학 성취도가 없으면 *2를 주도록 수정하였습니다.
<br>
- 수학에 대한 예외 처리 코드 추가
<br>
> fix(user): 수학 성취도 없으면 C 성적으로 산출되도록 수정

- apps/admin/src/services/form/mutations.ts
> 초안제출 상태인데 상태를 강제로 합격으로 만들어서 최종제출 상태로 변경 시킨 후 제출 서류 조회를 클릭 시 제출 서류를 찾을 수가 없어서 무한 로딩을 하는 상태에 빠지는 오류를 해결 했습니다.
<br>
- 최종제출 상태인데 최종제출 서류가 없을 경우 alert 추가
<br>
> fix(admin): 최종제출 서류가 없을 경우 alert 추가

- apps/user/src/app/form/초안작성완료/초안작성완료.tsx
> 초안제출시 애니메이션이 나오는데 이때 각 항목별 count하는 박스를 클릭하면 그 페이지로 이동하는데 이 점이 유저에게 안좋은 유저경험을 제공할거라고 판단하여 이를 해결하였습니다.
<br>
- 애니메이션 노출시 클릭 안되도록 수정
<br>
> fix(user): 애니메이션 중 클릭시 다른 페이지로 이동하는 문제 해결

- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
> 교무부 시연 당시 원서작성할때 페이지마다 빈칸이 있으면 넘어가지 않고 입력되지 않은 부분을 알려주라는 요청으로 수정하게되었습니다.
이번에 고입검정 입력 방법을 바꾸면서 입력 조건을 충족해야지 넘어가도록 수정하였습니다.
<br>
- 출신학교및학력의 조건을 추가하여 맞지 않으면 다음을 누르면 알려주고 맞으면 넘어가도록 수정
<br>
> fix(user): 출신학교및학력의 조건이 맞지 않은데 다음으로 넘어갈려고 할 시 에러메시지 띄우도록 수정

- apps/user/src/app/form/초안작성완료/초안작성완료.hooks.ts
- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
- apps/user/src/components/form/CheckFormCompleteBox/CheckFormCompleteBox.tsx
> 출신학교및학력이 졸업, 졸업예정일때 조건이 충족하더라도 넘어가지지 않는 문제가 있음. 또한 고입검정은 2가지만 입력하는데 초안제출할때는 9개라고 나와 유저에게 혼란을 줄 수 있어 이를 수정해야 했습니다.
<br>
- 고입검정일 경우 2개, 아닐경우 9개로 초안제출에 표시되도록 수정
- 유효성 검사 조건 수정
<br>
> fix(user): 고입검정일 경우 2개, 아닐 경우 9개로 표시되도록 수정

- apps/user/src/app/form/전형선택/전형선택.tsx
- packages/ui/src/Radio/Radio.tsx
> 고입검정으로 지원가능한 전형은 일반전형뿐입니다. 그래서 고입검정이 아닐때 전형을 다른걸로 지원하고 다시 고입검정으로 바꾸면 자동으로 일반전형으로 지원되도록 되어있고 고입검정에서 다른 전형선택하면 alert가 띄우면서 일반전형으로 선택됨. 하지만 이가 사용자에게 불편함을 줄수 있어 고입검정때는 일반전형만 선택가능하고 나머지는 disabled로 수정됩니다.
<br>
- Radio버튼에 disabled 추가
- 고입검정일때만 disabled되도록 조건 추가
<br>
> fix(user): 고입검정이면 전형선택시 일반 전형 제외 나머지의 Radio 버튼은 disabled로 수정

- apps/user/src/components/common/Header/Header.tsx
>일정에 따라 헤더가 수정되도록 했습니다.
입학 전형 기간이 아닐때는 홈, 성적 모의 계산, 공지사항, 자주 묻는 질문 순으로
원서 작성 기간일때는 홈, 원서 작성, 원서 관리, 공지사항, 자주 묻는 질문 순,
원서 작성 마감 후 입학 전형 기간에는 홈, 원서 관리, 공지사항, 자주 묻는 질문 순으로 나열되도록 수정되었습니다.
<br>
- 일정 조건 추가
- 일정 조건에 따른 헤더 수정
<br>
> fix(user): 일정에 따라 헤더 부분들이 달라지도록 수정

- apps/admin/src/app/form/page.tsx
> 2차 합격자 선택 시 아무 것도 선택 안 했을 시 버튼을 disabled로 하고 아니면 primary로 설정했습니다.
<br>
- 버튼 styleType 추가
<br>
> feat(admin): 2차 합격자 아무 것도 선택 안 했을 시 버튼 disabled

- apps/user/package.json
- apps/user/src/components/form/CropImageModal/CropImageModal.tsx
- apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
- apps/user/src/components/form/index.ts
- apps/user/src/utils/cropImage.ts
- apps/user/src/utils/index.ts
- pnpm-lock.yaml
> 사진 규격이 117*156이어야만 사진이 등록이 된다. 하지만 이보다 크면 규격에 맞게 사진을 잘라서 등록하도록 해야하는 것이 좋다고 하여 이를 위해 개발을 했습니다.
<br>
- 117*156으로만 사진이 자르도록 util 추가
- 사진을 선택하고 크면 자르는 모달이 뜨고 같다면 바로 등록이 되도록 로직 수정
<br>
처음에는 사진을 넣으면 자동으로 사진의 크기를 117*156으로 작아지도록 기능을 canvas를 사용하여 개발했었는데 사진이 많이 안 좋아져서 라이브러리를 사용하기로 했었는데 react-easy-crop이 우리가 원하던 라이브러리와 가장 흡사하여 이를 사용했는데 자를때는 화질이 그대로였다가 자르고 나면 사진 화질이 급격하게 낮아져 이를 고쳐 조금은 화질이 개선되도록 하였습니다. 하지만 다른 라이브러리나 해당 라이브러리를 유지하고 화질이 낮아지지 않도록 하는 방법은 없는지 궁금합니다.
https://github.com/user-attachments/assets/36b3e14f-fbd9-48a7-beff-7223da5e7b7d
> feat(user): 사진 규격보다 크면 규격만큼 자르는 기능 개발
