- src/styles/global.style.ts
- ADD :: common, ui
> default font와 폴더 구조화를 섬세하게 하였습니다
<br>
<br>
> ADD :: default font

- src/types/common/tooltip.type.ts
- src/types/utils/singlePropFrom.type.ts
> types/ 폴더에 singlePropFrom.type.ts 파일 삭제하고 tooltip.type.ts 수정했습니다^^7
<br>
- 
<br>
> REFACTOR :: tooltip.type.ts 파일 수정

- src/types/common/tooltip.type.ts
> tooltip.type.ts 폴더에 type을 interface로 수정하고 types 폴더에 utils 폴더 삭제했습니다
<br>
- 
<br>
> FIX :: tooltip.type.ts에서 type을 interface로 수정

- apps/user/src/app/layout.tsx
- apps/user/src/components/main/Dday/Dday.hooks.ts
> dayjs에 isBetween과 utc 기능에 나타난 에러 수정했습니다
<br>
<br>
> dayjs에 isBetween과 utc 기능에 나타난 에러 수정

- apps/user/src/components/common/Footer/Footer.tsx
> 디자인에 맞게 footer를 수정하였습니다 
<br>
<br>
> 디자인에 맞게 footer 수정

- apps/user/src/apis/instance/index.ts
- apps/user/src/apis/token/index.ts
- apps/user/src/apis/token/refresh.ts
- apps/user/src/apis/token/token.ts
- apps/user/src/app/login/page.tsx
- apps/user/src/app/notice/[detail]/page.tsx
- apps/user/src/components/common/Footer/Footer.tsx
- apps/user/src/components/common/Header/Header.tsx
- apps/user/src/components/main/Faq/Faq.tsx
- apps/user/src/components/main/Faq/FaqItem.tsx
- apps/user/src/components/main/Notice/Notice.tsx
- apps/user/src/components/main/Notice/NoticeItem.tsx
- apps/user/src/components/notice/NoticeItem/NoticeItem.tsx
- apps/user/src/constants/key.ts
- apps/user/src/constants/routes.ts
- apps/user/src/constants/token.ts
- apps/user/src/services/auth/mutations.ts
- apps/user/src/services/faq/queries.ts
- apps/user/src/services/main/queries.ts
- apps/user/src/services/notice/queries.ts
- packages/maru-ui/components/Dropdown/Dropdown.tsx
> constants object 형식으로 변경하였습니다
<br>
<br>
https://github.com/tooooo1/whoplus/blob/main/src/constants/routes.ts
염탐하다 더 좋은 방법 발견하고 바꿈 !
> constants object 형식으로 변경

- apps/user/src/app/form/page.tsx
- apps/user/src/app/login/login.hooks.ts
- apps/user/src/app/login/page.tsx
- apps/user/src/app/signup/page.tsx
- apps/user/src/app/signup/signup.hooks.ts
- apps/user/src/components/form/지원자정보/ProfileUpload.tsx
- apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.hooks.ts
- apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.tsx
- apps/user/src/components/form/지원자정보/지원자정보.hooks.ts
- apps/user/src/components/form/지원자정보/지원자정보.tsx
- apps/user/src/components/main/Dday/Dday.hooks.ts
- apps/user/src/services/form/지원자정보/api.ts
- apps/user/src/services/form/지원자정보/mutations.ts
- packages/maru-hooks/package.json
- packages/maru-hooks/src/useInterval.ts
- packages/maru-ui/components/Dropdown/Dropdown.tsx
- packages/maru-ui/components/Flex/Flex.type.ts
- packages/maru-ui/components/Radio/Radio.tsx
- packages/maru-ui/index.ts
- pnpm-lock.yaml
> 원서접수 지원자 정보 퍼블리싱을 하였습니다
<br>
<br>
> 원서접수 지원자 정보 개발

- apps/user/src/app/form/page.tsx
- apps/user/src/components/form/성적입력/성적입력.tsx
> 원서접수 성적입력 페이지에 프레임을 개발했습니다.
<br>
<br>
> 원서접수 성적입력 페이지 프레임 개발

- apps/user/src/app/form/page.tsx
- apps/user/src/components/form/FormController/FormController.tsx
- apps/user/src/components/form/ProgressBar/ProgressBar.tsx
- apps/user/src/components/form/index.ts
- apps/user/src/components/form/보호자정보/보호자정보.tsx
- apps/user/src/components/form/자기소개서/자기소개서.tsx
- apps/user/src/components/form/전형선택/전형선택.tsx
- apps/user/src/components/form/지원자정보/지원자정보.tsx
- apps/user/src/components/form/출신학교및학력/출신학교및학력.tsx
- apps/user/src/components/notice/NoticeHeader/NoticeHeader.tsx
- apps/user/src/layouts/FormLayout.tsx
- packages/maru-ui/components/Dropdown/Dropdown.tsx
- packages/maru-ui/components/Input/ButtonInput.tsx
- packages/maru-ui/components/Input/Input.tsx
- packages/maru-ui/components/Input/PreviewInput.tsx
- packages/maru-ui/components/Input/TimeLimitInput.tsx
- packages/maru-ui/components/Textarea/Textarea.tsx
- packages/maru-ui/index.ts
> 원서접수 자기소개서 페이지 개발을 하였습니다
<br>
<br>
> 원서접수 자기소개서 개발

- apps/user/src/app/page.tsx
- apps/user/src/components/main/Dday/Dday.tsx
- apps/user/src/components/main/Schedule/Schedule.tsx
> 스케쥴 컴포넌트 바뀐 디자인을 수정하였습니다
<br>
<br>
> 스케쥴 컴포넌트 바뀐 디자인 수정

- apps/user/src/apis/instance/instance.ts
- apps/user/src/apis/token/refresh.ts
- apps/user/src/components/main/Dday/Dday.tsx
> 리프래쉬 토큰 재발급 오류를 수정하였습니다
<br>
<br>
> 리프래쉬 토큰 재발급 오류 수정

- apps/user/src/app/form/성적입력/성적입력.tsx
- apps/user/src/components/common/Header/Header.tsx
- packages/maru-ui/index.ts
- packages/maru-ui/src/Button/Button.style.ts
- packages/maru-ui/src/Button/Button.type.ts
- packages/maru-ui/src/Button/UnderLineButton.tsx
- packages/maru-ui/src/Link/Link.tsx
> 스타일에서 크게 벗어나는 버튼을 분리하였습니다
<br>
<br>
> @maru/ui 버튼 분리

- apps/user/src/app/form/초안작성완료/초안작성완료.tsx
- apps/user/src/app/form/초안제출완료/초안제출완료.tsx
- apps/user/src/app/form/최종제출완료/최종제출완료.tsx
- apps/user/src/components/form/CompleteAlaram/CompleteAlaram.tsx
- apps/user/src/services/form/mutations.ts
- apps/user/src/types/form/client.ts
> 원서접수 최종제출완료를 개발하였습니다
<br>
<br>
> 원서접수 최종제출완료 개발

- apps/user/src/apis/token/token.ts
- apps/user/src/app/form/최종제출/최종제출.hooks.ts
- apps/user/src/app/form/최종제출/최종제출.state.ts
- apps/user/src/constants/token.ts
- apps/user/src/hooks/state/useFormStepState.ts
- apps/user/src/services/form/api.ts
- apps/user/src/services/form/mutations.ts
- apps/user/src/services/form/queries.ts
- apps/user/src/types/form/client.ts
> 원서접수 원서 초안 다운로드 개발을 하였습니다
<br>
<br>
잘나옴 ㅎㅎ
> 원서접수 원서 초안 다운로드 개발

- apps/user/src/apis/token/token.ts
- apps/user/src/services/form/api.ts
> Authorization.FormData를 추가하였습니다
<br>
<br>
> token.ts 리팩토링

- apps/user/src/app/form/성적입력/성적입력.tsx
- apps/user/src/app/form/전형선택/전형선택.hooks.ts
- apps/user/src/app/form/전형선택/전형선택.state.ts
- apps/user/src/app/form/전형선택/전형선택.tsx
- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
- apps/user/src/components/faq/FaqList/FaqList.tsx
- apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
- apps/user/src/components/form/Calculators/GradePreview/GradePreview.hooks.ts
- apps/user/src/components/form/Calculators/GradePreview/GradePreview.tsx
- apps/user/src/components/main/Faq/MainFaqList/MainFaqList.tsx
- apps/user/src/components/main/Notice/MainNoticeList/MainNoticeList.tsx
- apps/user/src/components/notice/NoticeList/NoticeList.tsx
- apps/user/src/constants/form.ts
- apps/user/src/types/form/client.ts
- packages/maru-ui/src/Radio/RadioGroup.tsx
> 성적 입력 페이지에 모의 성적 계산 로직 구현했습니다
로직이 맞는 건지 확인 부탁드립니ㅏㄷ
<br>
<br>
> 성적 입력 페이지에 모의 성적 계산 로직 구현했습니다

- apps/user/src/components/common/Header/Profile/Profile.tsx
- packages/maru-ui/src/Dropdown/Dropdown.tsx
> ADD :: 깃허브 리뷰 반영

- apps/user/src/app/faq/page.tsx
- apps/user/src/app/form/초안작성완료/초안작성완료.tsx
- apps/user/src/app/login/page.tsx
- apps/user/src/app/notice/[id]/page.tsx
- apps/user/src/app/notice/page.tsx
- apps/user/src/app/page.tsx
- apps/user/src/app/signup/page.tsx
- apps/user/src/components/common/Header/Header.tsx
- apps/user/src/hooks/state/useFormStepState.ts
- apps/user/src/layouts/AppLayout.tsx
- packages/maru-theme/src/font.ts
> 바뀐 폰트 스타일과 그 외에 부수적인 것들을 수정했습니다.
원서 접수 완료 페이지 애니메이션도 추가했습니다.
https://github.com/Bamdoliro/marururu/assets/102217839/467b694c-d90f-4d67-8d5c-f9045b6ead4e
<br>
<br>
> 원서 접수 완료 페이지 애니메이션 추가하고 바뀐 디자인 적용했습니다

- apps/user/src/app/signup/page.tsx
- apps/user/src/app/signup/signup.hooks.ts
- apps/user/src/services/auth/mutations.ts
- packages/maru-ui/src/Input/ButtonInput.tsx
> 인증 전송 제한 로직 구현

- apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
- apps/user/src/components/form/DraftFormConfirm/DraftFormConfirm.tsx
- apps/user/src/components/form/FinalFormConfirm/FinalFormConfirm.tsx
- apps/user/src/hooks/useUser.tsx
- apps/user/src/types/form/client.ts
> 원서접수 출결상황 버그 수정

- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
- apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
> 출신학교 및 학력 페이지 입력란 수정했습니다.
학교 나이스번호는 직접 입력하게 했고 지역도 버튼인풋에서 그냥 인풋으로 바꾸고 수정할 수 있게 만들었습니다.
<br>
-
<br>
> 출신학교 및 학력 페이지 입력란 수정했습니다

- apps/user/src/app/form/전형선택/전형선택.tsx
- apps/user/src/components/form/FindSchoolModal/SchoolList/SchoolList.tsx
- apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
- apps/user/src/components/form/ProgressBar/ProgressBar.tsx
- apps/user/src/components/main/Faq/MainFaqList/MainFaqItem/MainFaqItem.tsx
- packages/maru-ui/src/CheckBox/CheckBox.tsx
- packages/maru-ui/src/Dropdown/Dropdown.tsx
- packages/maru-ui/src/Input/ButtonInput.tsx
- packages/maru-ui/src/Radio/Radio.tsx
> flex 유틸리티를 적용하면 한 줄로 깔끔해질 수 있는 플렉스 박스 8개에 flex 유틸리티를 적용했습니다.
<br>
-
<br>
> flex 유틸리티를 적용하면 깔끔해지는 플렉스 박스에 flex 유틸리티 적용했습니다.

- .vscode/settings.json
- apps/admin/.eslintrc.js
- apps/user/.eslintrc.js
- apps/user/src/hooks/useUser.tsx
- apps/user/src/services/auth/mutations.ts
- apps/user/src/services/faq/queries.ts
- apps/user/src/services/form/queries.ts
- apps/user/src/services/notice/queries.ts
- apps/user/src/services/user/queries.ts
> 부수러기 코드 없애고 코드 보완했습니다.
커밋 기록을 통해 수정사항들을 확인해주세요~
<br>
<br>
> 부수러기 코드 없애고 코드 보완하기

- apps/user/src/app/form/초안제출완료/초안제출완료.tsx
- apps/user/src/app/form/최종제출완료/최종제출완료.hooks.ts
- apps/user/src/app/form/최종제출완료/최종제출완료.tsx
> 최종제출완료 페이지 퍼블리싱 & 초안제출완료 페이지에 애니메이션 추가했습니다.

- apps/user/src/app/login/page.tsx
- apps/user/src/services/auth/mutations.ts
> 로그인 페이지에 아이디 글자를 이메일로 변경했습니다.
<br>
-
<br>
> 로그인 페이지에 아이디 글자를 이메일로 변경했습니다.

- apps/user/src/app/signup/page.tsx
- apps/user/src/components/form/Calculators/CertificateCalculator/CertificateCalculator.tsx
- apps/user/src/hooks/index.ts
- apps/user/src/hooks/useApiError.ts
- apps/user/src/mocks/handlers/index.ts
- apps/user/src/services/QueryClientProvider.tsx
- apps/user/src/services/auth/mutations.ts
- apps/user/src/services/form/mutations.ts
- packages/maru-ui/src/Input/ButtonInput.tsx
- packages/maru-ui/src/Input/ConditionalMessage.tsx
- packages/maru-ui/src/Input/Input.tsx
- packages/maru-ui/src/Input/Input.type.ts
- packages/maru-ui/src/Input/Message.tsx
- packages/maru-ui/src/Input/PreviewInput.tsx
- packages/maru-ui/src/Input/TimeLimitInput.tsx
> useApiError로 에러 핸들링을 하였습니다 & input errorMessage를 추가하였습니다
<br>
<br>
> useApiError로 에러 핸들링 & input errorMessage

- apps/user/src/app/form/전형선택/전형선택.tsx
- apps/user/src/types/form/client.ts
> 전형 선택 전형 테이블 수정을 하였습니다
<br>
<br>
> 전형 선택 전형 테이블 수정

- apps/user/src/app/form/보호자정보/보호자정보.tsx
- apps/user/src/app/form/초안작성완료/초안작성완료.hooks.ts
- apps/user/src/constants/form/initial.ts
- apps/user/src/types/form/client.ts
- packages/maru-ui/src/RadioGroup/RadioGroup.tsx
> 원서접수 보호자정보 보호자 관계 입력 필드 추가하였습니다
<br>
<br>
> 원서접수 보호자정보 보호자 관계 입력 필드 추가

- apps/user/src/apis/token/refresh.ts
- apps/user/src/app/form/성적입력/성적입력.hooks.ts
- apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
- apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
> 원서접수 subjectList 누락 버그 & accessToken undefined 버그를 수정하였습니다
<br>
<br>
> 원서접수 subjectList 누락 버그 & accessToken undefined 버그 수정

- apps/user/src/components/common/Wrappers/FormWrapper/FormWrapper.tsx
> 원서접수 2분마다 중간저장 로직을 구현하였습니다
<br>
<br>
> 원서접수 2분마다 중간저장 로직

- apps/user/src/components/common/Header/Header.tsx
> 헤더에 최대 너비 추가했습니다
<br>
-
<br>
> 헤더에 최대 너비 추가했습니다

- apps/user/src/app/layout.tsx
- turbo.json
> 구글 애널리틱스 적용을 하였습니다
<br>
<br>
> 구글 애널리틱스 적용

- .github/workflows/review.yml
> review.yml 깃허브 액션 추가를 하였습니다
<br>
<br>
> review.yml 깃허브 액션 추가

- apps/user/src/app/login/login.hooks.ts
- apps/user/src/app/login/page.tsx
- apps/user/src/app/signup/page.tsx
- apps/user/src/app/signup/signup.hooks.ts
- apps/user/src/components/common/Header/Profile/Profile.tsx
- apps/user/src/services/auth/api.ts
- apps/user/src/services/auth/mutations.ts
- apps/user/src/store/user/user.ts
- apps/user/src/types/auth/remote.ts
- apps/user/src/types/user/client.ts
> 회원가입 전화번호 인증으로 변경 하였습니다
<br>
<br>
> 회원가입 전화번호 인증으로 변경

- apps/user/src/app/mobile/page.tsx
- apps/user/src/app/page.tsx
- apps/user/src/middleware.ts
> 모바일 사용성 개선

- apps/user/src/app/faq/page.tsx
- apps/user/src/app/page.tsx
- apps/user/src/components/faq/FaqList/FaqItem/FaqItem.tsx
> 자주 묻는 질문 버그를 수정하였습니다
<br>
<br>
배포가 급해서 main에다 머지합니다
> 자주 묻는 질문 버그 수정

- apps/user/src/app/form/초안작성완료/초안작성완료.tsx
- apps/user/src/middleware.ts
> 미들웨어 고쳐고쳐~ 원서접수 최대 고쳐고쳐~
<br>
<br>
> 머리부터발끝까지핫픽스

- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
- apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
- apps/user/src/components/form/FindSchoolModal/SchoolList/SchoolList.tsx
- apps/user/src/types/form/client.ts
> 학교 번호 자동 입력 개발을 하였습니다
<br>
<br>
> 학교 번호 자동 입력 개발

- apps/user/src/app/score-simulation/page.tsx
- apps/user/src/app/signup/page.tsx
- apps/user/src/app/signup/signup.hooks.ts
- apps/user/src/components/common/Header/Header.tsx
- apps/user/src/components/main/SimulatorBox/SimulatorBox.tsx
- apps/user/src/constants/common/constant.ts
- apps/user/src/services/auth/api.ts
- apps/user/src/services/auth/mutations.ts
- apps/user/src/types/auth/client.ts
- apps/user/src/types/auth/remote.ts
- packages/maru-ui/src/Input/TimeLimitInput.tsx
> 인증번호 확인 기능 개발을 하였습니다
<br>
<br>
> 인증번호 확인 기능 개발

- apps/user/src/app/form/보호자정보/보호자정보.hooks.ts
- apps/user/src/app/form/보호자정보/보호자정보.tsx
- packages/maru-ui/src/RadioGroup/RadioGroup.tsx
> 보호자 관계 Input 추가를 하였습니다
<br>
<br>
> 보호자 관계 Input 추가

- apps/admin/src/components/common/SideBar/SideBar.tsx
- apps/admin/src/constants/common/constants.ts
> 어드민 사이드바 디자인을 반영했습니다.
<br>
<br>
> 어드민 사이드바 디자인 반영

- apps/admin/src/components/common/SideBar/SideBar.tsx
- packages/maru-theme/src/font.ts
> H5 폰트 굵기 수정했습니다.
<br>
-
<br>
> H5 폰트 굵기 수정

- apps/user/src/components/main/Schedule/Schedule.tsx
- apps/user/src/components/main/Schedule/ScheduleItem/ScheduleItem.tsx
- apps/user/src/constants/form/constant.ts
> 일정 컴포넌트 디자인 수정하였습니다
<br>
- 컴포넌트 디자인에 맞게 퍼블리싱
- dayjs를 통한 item active 기능
<br>
costants 네이밍 부분 봐주세요.. 제가 봐도 억지 느낌.. 그리고 between이 필요없는것들이 충분히 있다고 봅니다! 여기에 대한 개선점을 말씀해주세요!!
https://github.com/Bamdoliro/marururu/assets/102217654/86d10dcd-bf2c-4f13-9ceb-da839821cc53
> 일정 컴포넌트 디자인 수정

- apps/admin/src/app/faq/[id]/page.tsx
- apps/admin/src/app/faq/edit/[id]/page.tsx
- apps/admin/src/app/notice/[id]/page.tsx
- apps/admin/src/components/faq/FaqDetailContent/FaqDetailContent.tsx
- apps/admin/src/components/faq/FaqEdit/FaqEdit.hooks.ts
- apps/admin/src/components/faq/FaqEdit/FaqEdit.tsx
- apps/admin/src/components/notice/NoticeEdit/NoticeEdit.tsx
- apps/admin/src/constants/common/constant.ts
- apps/admin/src/services/faq/api.ts
- apps/admin/src/services/faq/mutations.ts
- apps/admin/src/types/faq/client.ts
- apps/admin/src/types/faq/remote.ts
> 어드민 자묻질 수정하기 기능을 개발했습니다.
<br>
- 어드민 자묻질 수정하기 기능 개발
<br>
https://github.com/Bamdoliro/marururu/assets/102217839/918a0f01-ed4e-4006-a8f1-ee3904f2112e
> 어드민 자주 묻는 질문 수정하기 개발

- apps/admin/package.json
- apps/admin/src/components/form/FormDetailContent/FormDetailContent.tsx
- apps/admin/src/components/form/FormDetailContent/Profile/Profile.tsx
- apps/admin/src/components/form/FormDetailContent/지원자정보/지원자정보.tsx
- pnpm-lock.yaml
> 어드민 원서 상세조회에서 지원자 페이지를 개발했습니다.
<br>
- 어드민 원서 상세조회 지원자 페이지 개발
<br>
https://github.com/Bamdoliro/marururu/assets/102217839/f339a3a3-ac77-44ff-a3ed-6c5d5f921cd1
> 어드민 원서 상세조회 지원자 페이지 개발

- apps/admin/src/components/form/FormDetailContent/지원자정보/지원자정보.tsx
> 어드민 원서 상세조회 지원자 정보 페이지를 수정했습니다.
<br>
- 어드민 원서 상세조회 지원자정보 페이지 수정
<br>
> 어드민 원서 상세조회 지원자 정보 페이지 수정

- apps/admin/src/components/form/FormDetailContent/FormDetailContent.tsx
- apps/admin/src/components/form/FormDetailContent/보호자정보/보호자정보.tsx
> 어드민 원서 상세 페이지에서 보호자 정보 페이지를 개발했습니다.
<br>
- 어드민 원서 상세 보호자 정보 페이지 개발
<br>
> 어드민 원서 상세 보호자 정보 페이지 개발

- apps/admin/src/components/common/DataBox/DataBox.tsx
- apps/admin/src/components/form/FormDetailContent/FormDetailContent.tsx
- apps/admin/src/components/form/FormDetailContent/자기소개서/자기소개서.tsx
- apps/admin/src/components/form/FormDetailContent/전형/전형.tsx
- apps/admin/src/components/form/FormDetailContent/출신학교및학력/출신학교및학력.tsx
- packages/maru-ui/src/Text/Text.tsx
> 어드민 원서 상세 페이지에 출신학교 및 학력, 전형, 자기소개서 페이지를 개발했습니다.
<br>
- 출신학교 및 학력 페이지 개발
- 전형 페이지 개발
- 자기소개서 페이지 개발
<br>
https://github.com/Bamdoliro/marururu/assets/102217839/b4830167-fe7e-49f9-8880-6734ac7d3e35
> 어드민 원서 상세 출신학교 및 학력, 전형, 자기소개서 페이지 개발

- apps/admin/src/components/form/FormDetailContent/ChangeFinalScoreModal/ChangeFinalScoreModal.hooks.ts
- apps/admin/src/components/form/FormDetailContent/ChangeFinalScoreModal/ChangeFinalScoreModal.tsx
- apps/admin/src/components/form/FormDetailContent/FinalSubmissionConfirm/FinalSubmissionConfirm.tsx
- apps/admin/src/components/form/FormDetailContent/FormStatus/FormStatus.tsx
- apps/admin/src/services/form/api.ts
- apps/admin/src/services/form/mutations.ts
- apps/admin/src/types/form/client.ts
> 어드민 원서 최종 접수 확인 모달창을 개발했습니다.
<br>
- 어드민 원서 최종 접수 확인 모달창 퍼블리싱
- 어드민 원서 최종 접수 확인 api 연결
<br>
https://github.com/Bamdoliro/marururu/assets/102217839/5c1869b8-a779-4dff-b798-1bb5a27c8b29
> 어드민 원서 최종 접수 확인 모달창 개발

- apps/user/src/app/form/최종제출/최종제출.hooks.ts
- apps/user/src/app/form/최종제출/최종제출.tsx
- apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
- apps/user/src/hooks/index.ts
- apps/user/src/hooks/useOpenFileUploader.ts
> 여러 파일에서 똑같은 로직에 파일 업로드 로직이 발견되어 가독성을 위해 custom hook으로 추상화 하였습니다
<br>
<br>
> useOpenFileUploader로 추상화

- apps/user/src/components/common/Wrappers/AuthWrapper/AuthWrapper.tsx
- apps/user/src/components/common/Wrappers/AuthWrapper/FormPeriodModal/FormPeriodModal.tsx
- apps/user/src/components/common/Wrappers/AuthWrapper/LoginRequiredModal/LoginRequiredModal.tsx
> AuthWrapper에 개선점이 보여서 리팩토링을 하였습니다
<br>
<br>
> AuthWrapper 리팩토링

- apps/admin/src/app/form.hooks.ts
- apps/admin/src/app/page.tsx
- apps/admin/src/components/form/FormTable/FormTableHeader/FormTableHeader.tsx
- apps/admin/src/components/form/FormTable/FormTableItem/FormTableItem.tsx
- apps/admin/src/components/form/SecondScoreUploadModal/SecondScoreUploadModal.hooks.ts
- apps/admin/src/components/form/SecondScoreUploadModal/SecondScoreUploadModal.tsx
- apps/admin/src/constants/common/constant.ts
- apps/admin/src/services/form/api.ts
- apps/admin/src/services/form/mutations.ts
- apps/admin/src/services/form/queries.ts
- apps/admin/src/store/form/formToPrint.ts
- apps/admin/src/store/form/isFormToPrintSelecting.ts
- apps/admin/src/store/form/isSecondRoundResultEditing.ts
- apps/admin/src/store/form/secondRoundResult.ts
- apps/admin/src/types/form/remote.ts
> 어드민 원서 출력하기 기능을 개발했습니다.
<br>
- 어드민 원서 출력하기 기능 개발
<br>
https://github.com/Bamdoliro/marururu/assets/102217839/97685677-07aa-468f-9ec6-f7140c0677e9
> 어드민 원서 출력하기 기능 개발

- .github/workflows/lighthouse-ci.yml
- .lighthouserc.js
- package.json
- pnpm-lock.yaml
> Lighthouse CI와 Github Actions를 연동하여 성능 측정 및 Lighthouse 보고서 생성을 자동화하는 과정을 구축하였습니다
<br>
- Lighthouse ci 추가
<br>
> feat: lighthouse ci 추가

- apps/user/src/constants/form/constant.ts
> 영어로 표시되던 DdayBox를 한글로 고쳤습니다.
<br>
- DdayBox 요일 한글로 바꾸기
<br>
> fix(user): DdayBox 한글 요일로 변경

- apps/user/src/components/main/ApplicationSubmittionBox/DdayBox/DdayBox.hooks.ts
> fix(user): 글자 수정

- apps/user/src/components/main/ApplicationSubmittionBox/ApplicationSubmittionBox.hooks.ts
- apps/user/src/components/main/ApplicationSubmittionBox/DdayBox/DdayBox.hooks.ts
> fix(user): 입학 등록 기간 추가

- apps/admin/src/app/login/login.hooks.ts
- apps/admin/src/app/login/page.tsx
- apps/user/src/app/login/page.tsx
- packages/ui/src/Input/PreviewInput.tsx
> User와 Admin에서 Enter로 로그인되게 했습니다
<br>
- User에서 로그인 Enter 기능 추가
- Admin에서 로그인 Enter 기능 추가
<br>
> feat(user, admin): 로그인 및 회원가입에서 enter 기능 개발

- apps/admin/src/app/faq/page.tsx
- apps/admin/src/components/faq/FaqTable/FaqTable.tsx
- apps/admin/src/types/faq/client.ts
> FAQ 카테고리별 검색기능으로 카테고리별, 전체 게시물별로 볼수 있도록 했습니다.
<br>
- 드롭다운에 value와 label이 들어간 data배열을 만들었습니다.
- 전체보기와 학교 생활등 그외의 카테고리별로 게시물을 볼 수 있는 기능을 개발했습니다.
<br>
> feat(admin): 카테고리별 검색 기능 추가

- apps/user/src/app/form-management/page.tsx
- apps/user/src/components/form-management/CallForInquiries/CallForInquiries.tsx
- apps/user/src/components/form-management/CheckFrom/CheckForm.hooks.ts
- apps/user/src/components/form-management/WriteNextForm/WriteNextForm.tsx
> 원서 관리 페이지에서 갭과 상자의 너비를 수정하였습니다
<br>
- 원서 관리 페이지에서 갭과 상자의 너비를 수정하였습니다
- hook을 수정하여 로그인과 alert가 사라졌습니다
<br>
> feat(user): 원서 관리 페이지 갭과 너비 수정 및 hook 수정

- apps/user/src/components/main/ScheduleBox/ScheduleBox.tsx
- apps/user/src/constants/form/constant.ts
> 2025학년도 신입생들의 입학 일정으로 수정하였습니다.
<br>
- 2025학년도 신입생들의 입학 일정으로 수정
<br>
> FIX(user): 2025학년도 신입생 모집 일정으로 수정

- apps/user/src/apis/instance/instance.ts
- apps/user/src/components/common/Header/Header.tsx
- apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
- apps/user/src/components/main/GuardFormModal/GuardFormModal.tsx
- apps/user/src/components/main/ScheduleBox/ScheduleBox.tsx
- apps/user/src/components/main/ScheduleBox/ScheduleBoxItem/ScheduleBoxItem.tsx
- apps/user/src/constants/form/constant.ts
- packages/ui/src/Modal/Modal.tsx
> 원서 작성 페이지는 일정에 맞을 경우에만 들어가지도록 하였습니다.
> 현재 원서 작성 일정은 QA 및 중간 발표회 시연영상을 위해서 6월13일부터 7월31일까지로 수정해놓았습니다.
<br>
- 디데이가 아닌데 원서를 작성할려고 하면 모달이 뜨도록 하였습니다.
- 일정에 해당하는 것만 활성화되도록 수정하였습니다.
<br>
> fear(user): 원서 작성 일정이 아니면 들어가지 못하도록 수정

- apps/user/src/components/common/Header/Header.tsx
- apps/user/src/components/main/NeedLoginModal/NeedLoginModal.tsx
- packages/ui/src/Modal/Modal.tsx
> 로그인이 안되어 있으면 원서관리, 원서 작성이 불가능하도록 모달을 띄워주도록 했습니다.
<br>
- 로그인이 안되어 있을때 원서 작성, 관리로 진입이 가능한지 확인했습니다.
- 로그인이 되었을때 같은 이벤트가 나오는지 확인했습니다.
<br>
https://github.com/Bamdoliro/marururu/assets/126876363/873b9221-71ce-4c94-9b53-b1e603b5ca7a
> feat(user): 로그인이 안되어 있을시 원서관리, 원서 작성 페이지 진입 못하고 로그인 페이지로 이동하도록 기능 개발

- apps/user/next.config.js
- apps/user/src/components/common/Header/Header.tsx
> 로그인이 안되어 있으면 모달이 뜸
> 원서 작성 기간이 아닐때 모달이 뜸
> url로 접근할려고 할때 막음
<br>
- url을 직접 들어가려고 하면 메인으로 가도록 차단함
- 원서 접수 기간이 아닐때 작성및 관리 페이지에 들어가려고 하면 모달을 띄움
- 로그인이 안되어 있는데 작성 및 관리 페이지에 들어가려고 하면 모달을 띄움
<br>
> feat(user): 입학 접수기간 아닐때 원서 작성 및 원서 관리 페이지에 접근하려고 할때의 기능 개발

- apps/user/src/components/form-management/FormStatus/FormStatus.tsx
> 반려, 최종 제출, 승인만 있던 formStatus에서 추가했습니다.
<br>
- 반려, 최종 제출, 승인 이외에 원서 상태에 대해서 추가 개발 했습니다.
<br>
> feat(user): formStatus에 맞는 박스 추가

- apps/user/src/app/form/초안작성완료/초안작성완료.hooks.ts
- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
- apps/user/src/components/form-management/FormStatus/FormStatus.tsx
- apps/user/src/components/form/CheckFormCompleteBox/CheckFormCompleteBox.tsx
- apps/user/src/components/form/FindSchoolModal/FindSchoolModal.tsx
- apps/user/src/components/form/FindSchoolModal/SchoolList/SchoolList.tsx
- apps/user/src/constants/form/data.ts
- apps/user/src/types/form/client.ts
> 학교 선택시 표준코드, 지역만 자동완성되던 것이 도로명주소도 함께 자동완성 기능 추가 개발하였습니다.
<br>
- 도로명주소가 자동완성되도록 수정했습니다.
- 초안제출시 원서 비어있는 것 확인을 위한 개수를 수정했습니다.
<br>
> feat(user): 학교 선택시 도로명주소도 함께 자동완성 기능 추가

- .github/CODEOWNERS
CODEOWNERS에 정홍섭, 오아린, 이민준을 업데이트를 하였습니다
>
<br>
<br>
> feat(common): CODEOWNERS 업데이트

- apps/admin/src/components/form/FormDetailContent/출신학교및학력/출신학교및학력.tsx
- apps/admin/src/types/form/client.ts
>상세 원서 조회에서 도로명주소가 보이도록 수정하였습니다.
<br>
-상세 원서 조회에서 출신학교 및 학력에서 학교 도로명주소가 보이도록 수정
-axios로 가져오기 위해서 client.ts에서 schoolAddress를 추가
<br>
> feat(admin): 변수명 추가 및 상자 추가

- apps/admin/src/app/fair/page.tsx
- apps/admin/src/components/fair/FairItem/ApplyingItem.tsx
- apps/admin/src/components/fair/FairItem/ClosedItem.tsx
- apps/admin/src/components/fair/FairList/ApplyingList.tsx
- apps/admin/src/components/fair/FairList/ClosedList.tsx
- apps/admin/src/components/fair/Header/header.tsx
- apps/admin/src/services/fair/queries.ts
- apps/user/src/components/form-management/FormStatus/FormStatus.tsx
>입학설명회 학생 교사 일정 리스트가 구분되도록 수정하였습니다.
<br>
-입학설명회 일정 리스트 디자인을 수정하였습니다.
-원서 상태의 아이콘을 수정하였습니다.
<br>
> fix(admin): 입학설명회 학생 교사 아이템 구분

- apps/user/src/app/form/최종제출/최종제출.tsx
- apps/user/src/components/form/DraftFormConfirm/DraftFormConfirm.tsx
- apps/user/src/services/form/api.ts
- apps/user/src/services/form/mutations.ts
- packages/ui/index.ts
- packages/ui/src/Confirm/Confirm.tsx
- packages/ui/src/Input/CheckInput.tsx
>초안을 제출하기 위해서 정보가 틀리지 않았고 다시 한번 확인하도록 해서 학교와 밤돌이로에 책임이 없다고 고지하기 위해서 특정 문구를 입력해야지 다음 단계로 넘어가도록 수정하였습니다.
<br>
- 문구를 추가했습니다.
- 정해진 문구와 입력된 문구가 일치하면 다음 단계로 넘어가도록 수정하였습니다.
- 디자인에 맞는 인풋창을 추가했습니다.
<br>
> feat(user): 초안제출시 다음 단계로 넘어가기 위해서 특정 문구를 입력해야 넘어가도록 수정

- apps/user/src/app/form/page.tsx
>원서 반려시 최종제출 페이지로 이동하여 재제출 기능 개발
<br>
-원서 상태가 REJECTED라면 최종제출 페이지로 이동하여 수정한 원서를 제출할도록 수정
<br>
> feat(user): 원서 반려시 최종제출 페이지로 이동하여 재제출 기능 개발

- apps/user/src/app/form/초안작성완료/초안작성완료.tsx
- apps/user/src/components/common/Footer/Footer.tsx
- apps/user/src/components/form-management/FormStatus/FormStatus.tsx
- apps/user/src/components/main/ApplicationSubmittionBox/ApplicationPeriodBox/ApplicationPeriodBox.tsx
>원서 초안 작성 실패시 처음으로 돌아가기 버튼 추가등 여러가지를 수정했습니다.
<br>
- 원서 초안 작성 실패시 처음으로 돌아가기 버튼 추가
- 푸터에서 학교 홈페이지로 이동하도록 수정
- 학교 외부인이 원서 작성을 하지 못하게 경고문으로 임시 변경
- 원서 상태별 아이콘 추가 수정
<br>
> feat(user): 원서 초안 작성 실패시 처음으로 돌아가기 버튼 추가

- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
- apps/user/src/components/form/Calculators/ScoreCalculator/GEDCalculator/GEDCalculatorItem/GEDCalculatorItem.hooks.ts
- apps/user/src/components/form/Calculators/ScoreCalculator/GEDCalculator/NewGEDCalculatorItem/NewGEDCalculatorItem.hooks.ts
- apps/user/src/components/form/DraftFormConfirm/DraftFormConfirm.tsx
- apps/user/src/components/main/GuardFormModal/GuardFormModal.tsx
- apps/user/src/components/main/NeedLoginModal/NeedLoginModal.tsx
- apps/user/src/components/signup/Terms/Terms.tsx
- packages/design-token/src/global.ts
- packages/ui/src/Input/CellInput.tsx
- packages/ui/src/Text/Text.tsx
>회원가입시 약관 2개만 해도 가능한 것을 수정 했습니다.
고입 검정 성적 입력 수가 무한히 가능한 것을 수정했습니다.
웹 폰트 문제를 해결했습니다.
<br>
-회원가입시 약관 2개만 해도 가능한 것을 수정 했습니다.
고입 검정 성적 입력 수가 무한히 가능한 것을 수정했습니다.
웹 폰트 문제를 해결했습니다.
<br>
> feat(user): QA 동안의 오류 일부 수정

- apps/user/src/components/signup/validate/Validate.tsx
>회원가입 중 특수문자는 !@#$%&*?만 입력이 가능하다는 것을 나타내기 위해서 문구를 수정하였습니다.
<br>
-!@#$%&*?만 입력 가능하다는 문구로 수정
<br>
> fix(user): 특수문자 확인 문구 수정

- apps/user/src/app/form/지원자정보/지원자정보.tsx
>유저가 생년월일 기입을 어떤 형식으로 입력하는지 placeholder를 수정하여 유저가 쉽게 알수 있도록 수정하였습니다.
<br>
-생년월일 placeholder 글 수정
<br>
> fix(user): 생년월일 placeholder 글 수정

- apps/user/src/app/change-password/page.tsx
- apps/user/src/app/signup/page.tsx
- packages/ui/src/Input/TimeLimitInput.tsx
> 회원가입시 인증번호를 입력하려는 인풋은 생기면서 에러 메시지가 뜨는데 이를 지우고 placeholder로 인증번호를 입력하라고 유저에게 표시하도록 수정하였습니다.
<br>
-회원가입 인풋 간격 수정
<br>
> fix(user): 회원가입 인풋 간격 수정

- apps/user/src/components/common/Header/Profile/Profile.hooks.ts
- apps/user/src/components/common/Header/Profile/Profile.tsx
- apps/user/src/services/auth/mutations.ts
>로그인 후 드롭다운 내에서 원서 작성 및 로그아웃에서 비밀번호 변경 아이템을 추가하였습니다.
<br>
- 드롭다운 내 추가
- 비번 변경후 토큰 삭제
<br>
> fix(user): 비번 변경을 프로필 드롭다운에 추가

- apps/user/src/components/form/Calculators/ScoreCalculator/GEDCalculator/GEDCalculatorItem/GEDCalculatorItem.hooks.ts
- packages/ui/src/Input/CellInput.tsx
> 성적을 입력할때 봉사시간 및 출결 입력할 때는 소수점 입력이 불가하므로 이를 막았습니다.
숫자를 입력하면 초기값으로 0에서 앞에 0이 있는 상태에서 입력되는 현상을 수정하였습니다.
<br>
- 소수점 입력 안되도록 수정
- '01'을 '1'로만 입력되게 수정
<br>
<br>
https://github.com/Bamdoliro/marururu/assets/126876363/079ceb96-391f-4cf2-8ce7-2341516b7e9f
> fix(packages): 성적입력에서 봉사시간 및 출결 입력시 소수점 및 0+숫자로 입력되는 현상 수정

- apps/admin/src/app/fair/page.tsx
> 입학설명회 관리 페이지 스타일이 잘못 지정되어 있어 이를 수정했습니다.
<br>
- 입학설명회 관리 페이지 스타일 수정
<br>
> fix(admin): 입학설명회 관리 페이지 스타일 수정

- apps/admin/src/components/form/FormDetailContent/출신학교및학력/출신학교및학력.tsx
- apps/admin/src/types/form/client.ts
- apps/user/src/app/form/초안작성완료/초안작성완료.hooks.ts
- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
- apps/user/src/constants/form/data.ts
- apps/user/src/types/form/client.ts
> 어드민 상세 원서 학교 연락처가 안 보이는 오류를 해결 했습니다.
> 백엔드와 동일한 타입 명을 사용하게 수정 했습니다.
<br>
- teacherPhoneNumber 명칭을 schoolPhoneNumber으로 변경
<br>
> fix(user, admin): 학교 연락처 안 보이는 오류 해결

- apps/user/src/components/form/Calculators/ScoreCalculator/ScoreCalculator.tsx
> 성적입력을 하면 국어 수학 영어는 성취도가 없을시 -이지만 산출은 C와 같은 성적으로 나타나기에 이를 유저에게 알려주기 위해서 문구를 수정하였습니다.
<br>
- 기존문구를 새로운 문구로 수정
<br>
> fix(user): 성적입력 게산기 문구 수정

- apps/admin/src/components/form/FormTable/FormTableItem/FormTableItem.tsx
> 부동소수점으로 인해 소수점 셋째자리까지 안 나오고 초과해서 나오는 오류를 해결 하였습니다.
<br>
- 소수점 셋째자리까지 나오게 변경
<br>
> fix(admin): 부동소수점 -> 소수점 셋째자리 까지 변경

- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
> 원서작성을 해보던 중 출신학교및 학력 페이지로 넘어갈려고 할때 404페이지라는 에러를 발견하여 이를 수정했습니다.
<br>
- 에러 조건을 수정
- value 조건 수정
<br>
> fix(user): 원서작성중 학력 입력페이지 진입 안되는 에러 수정

- packages/ui/src/Dropdown/SubDropdown.tsx
> 2단 드롭다운의 위치가 겹치는 문제와 누른 후에 호버처럼 누른 티가 나게 수정했습니다.
<br>
- 2단 드롭다운 위치 수정
- focus 추가 
<br>
> fix(admin): 2단 드롭다운 위치 및 누른 후 호버 스타일 적용

- apps/user/src/app/form/최종제출/최종제출.tsx
> 디자인에서 최종제출 페이지의 경고메시지를 추가하여 이를 수정하였습니다.
<br>
- 텍스트 추가후 문구 추가
<br>
> fix(user): 최종제출 페이지 경고 문구 수정

- apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
>봉사시간이 학년별로 최대시간이 정해져있어 이를 알려주기 위해서 문구를 추가하였습니다.
<br>
- 문구 수정
<br>
> fix(user): 봉사시간 문구를 추가

- apps/admin/src/components/form/FormTable/FormTableItem/FormTableItem.tsx
> 2차 결과 드롭다운 중 미정 항목을 삭제했습니다.
<br>
- 미정 삭제
<br>
> fix(admin): 2차 결과 미정 삭제

- apps/user/src/app/form/보호자정보/보호자정보.hooks.ts
- apps/user/src/app/form/지원자정보/지원자정보.hooks.ts
- apps/user/src/app/form/출신학교및학력/출신학교및학력.hooks.ts
- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
> 부모 연락처, 생년월일, 교사연락처, 학교연락처는 숫자만 입력이 가능해야하는데 현재는 숫자뿐만 아니라 문자도 입력가능해서 이를 수정해야 했습니다.
<br>
- 부모 연락처 숫자만 입력 가능하도록 수정
- 생년월일 숫자만 입력 가능하도록 수정
- 교사 연락처 숫자만 입력 가능하도록 수정
- 학교 연락처는 숫자만 입력 가능하도록 수정
<br>
> fix(user): 부모 연락처, 생년월일, 교사연락처, 학교연락처는 숫자만 입력되도록 수정

- apps/user/src/components/common/Header/Profile/Profile.tsx
> 일정에 따라서 원서 작성 기간이 아니면 로그인 후 드롭다운에서 원서 작성 이어서 하기 아이템을 없애도록 하였습니다.
<br>
- 일정에 따라 프로필 아이템 다르도록 조건 추가
<br>
> fix(user): 일정에따라 프로필 드롭다운 아이템 수정

- apps/user/src/app/form/보호자정보/보호자정보.tsx
- apps/user/src/app/form/자기소개서/자기소개서.tsx
- apps/user/src/app/form/지원자정보/지원자정보.tsx
- apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
- apps/user/src/constants/form/constant.ts
- packages/ui/src/Textarea/ConditionalMessage.tsx
- packages/ui/src/Textarea/Textarea.tsx
> 교무부 시연 중 교무부 선생님들의 요청으로 원서 작성하고 페이지를 넘어갈 때마다 비어 있는 곳을 알려주도록 수정하였습니다.
출신학교및학력은 검정고시 입력에 대한 기능을 수정 개발한 후 다시 개발 할 예정입니다.
<br>
- 지원자의 정보에서 검증
- 보호자 정보에서 검증
- 자기소개서에서 검증
<br>
> fix(user): 원서 작성 중 입력되지 않으면 다음 페이지로 돌아가지 않도록 수정

- apps/user/src/app/form/초안작성완료/초안작성완료.hooks.ts
- apps/user/src/app/form/출신학교및학력/출신학교및학력.hooks.ts
- apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
- apps/user/src/types/form/client.ts
> 고입검정일 경우 졸업구분, 합격연도만 나오도록 수정하고 나머지는 null이여도 제출이 가능하도록 해야했습니다.
<br>
- 고입검정일경우 졸업구분, 합격연도를 제외하고는 null이여도 되도록 수정
- 고입검정이 아닐경우 모두 입력되도록 수정
- 초안작성 완료에서 고입검정 기준 수정
<br>
> fix(user): 고입검정 입력조건 수정

- apps/admin/src/components/faq/FaqEdit/FaqEdit.tsx
- apps/admin/src/components/faq/FaqPost/FaqPost.tsx
> 디자인과 다른 카테고리 크기를 조정했습니다
<br>
- 카테고리 post, edit에 width 추가
<br>
> fix(admin): 카테고리 크기 조정

- apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
> 증명사진을 업로드하고 다시 업로드하고 나면 미리보기 사진이 변경되지 않는 문제가 발생하였습니다. 문제를 확인하니 재업로드 후 post는 되었지만 get으로 사진을 불러오지 않아 미리보기 사진이 변경되지 않는 것을 확인했습니다. 그리고 그 문제를 해결하였습니다.
<br>
- 재업로드 사진 post후 get으로 사진 미리보기 기능 수정
<br>
> fix(user): 증명사진을 재업로드했을때 미리보기 사진이 변경되도록 수정
